ISSUE #41 - Pundit gem added
ErnestsEida/R-edited pull request #45
Opened 2021-11-17 09:30 UTC by ErnestsEida

- Pundit gem added
- Post editing now authorized with policy
- views adjusted

2021-11-17 10:18 UTC, pavels-gaimovics requested changes

2021-11-17 10:18 UTC, pavels-gaimovics commented on app/controllers/posts_controller.rb
> +    authorize @post
Pieliec post autorizaciju ari pie Update un Destroy.

Sanak kā tu tagad neļausi lietotajam atvērt redigešanas lapu svešam Post, bet sutit HTTP requestu ar PUT un DELETE viņš tā un tā vares.

2021-11-17 10:18 UTC, pavels-gaimovics commented on app/controllers/posts_controller.rb
>    def show
Man ir aizdomas kā tukšo metodi tu vari izņemt un viss strādās. Vai vari paprovet?

2021-11-17 10:18 UTC, pavels-gaimovics commented on app/views/posts/show.html.slim
> +      - if user_signed_in? && current_user.id == @post.user_id
Very good!

Bet posts_helper tagad tu nekur neizmanto un pagaidam vari to dzēst

2021-11-17 11:10 UTC, ErnestsEida commented on app/controllers/posts_controller.rb
>    def show
Ja , ari bez metodes viss strada

2021-11-19 07:38 UTC, pavels-gaimovics approved these changes
LGTM

2021-11-19 07:39 UTC, merged