ISSUE #22 - Search bar implemented
ErnestsEida/R-edited pull request #63
Opened 2021-12-02 12:27 UTC by ErnestsEida

- Search located in top right corner of screen ( inside header )
- provided search parameters will show users, posts and communities

Search bar:
<img width="648" alt="Screenshot 2021-12-02 at 14 25 48" src="https://user-images.githubusercontent.com/90070548/144421685-39baebcc-654a-4a77-bb23-e33675ff7af9.png">
Search Results:
<img width="1047" alt="Screenshot 2021-12-02 at 14 26 05" src="https://user-images.githubusercontent.com/90070548/144421678-6dda1c75-d554-4efe-90cd-40411a736450.png">

2021-12-02 14:29 UTC, pavels-gaimovics requested changes
Ļoti labi! Bet mazas lietas vajadzetu pielābot

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/assets/stylesheets/search.scss
> +#post-container{
Tev sanak tris sekcijas kuram ir vienadi css rules.

Šeit ut vari definet jaunu klasi un pielikt viņu iekš html, piemēram: ".search-results-section"

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/assets/stylesheets/search.scss
> +  h6{
Trukst atstrapes pēc h6!

Un vel, lieta tāda kā kad tu izmanto standartus html elementus priekš tekstam, viņu vajadzēs stingri nostīlot ar izveletu fontu un izmēru. Tāpēc kā katram pārlūkam patīk to radīt savā noteiktā veidā.

Pagaidām, kamēr tev vel nav sacies uzdevums ar nostilošanu, tu vari pielikt reset.css.
Viņš noņems visadus liekus stilus priekš html elementiem. Vari to uzlīkt ar yarn

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/assets/stylesheets/search.scss
> +.card:hover{
Atstrape!

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/controllers/search_controller.rb
> +    @query = params[:query]
Priekš kam tev @query kā instances mainigais?

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/controllers/search_controller.rb
> +    if @query != ""
Par to kadreiz bija saruna, kā salidzinošana iekš Ruby ar != un == var izsaukt coercion (implicit conversion)

if query.blank?

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/views/search/search_query.html.slim
> +    .card class="mb-3"
Klases nostilo pēc SLIM

2021-12-02 14:29 UTC, pavels-gaimovics commented on app/views/layouts/_header.html.slim
> +      = form_with url: "/search", method: :get do |f|
Izmanto priekš url helperus nevis pataisno url.

Paskaties komentaru pie routes

2021-12-02 14:29 UTC, pavels-gaimovics commented on config/routes.rb
> +  get "search", to: "search#search_query"
Man ir aizdomas, kā šeit tu vareji vnk:
get :search

un tad iekš contoleri nosaukt metodi par "show" un tev sanaktu stilitiski mazak lieko vārdu

2021-12-02 14:48 UTC, ErnestsEida commented on app/controllers/search_controller.rb
> +    @query = params[:query]
Vins itka tiek izmantots search skata, ka virsraksts

2021-12-03 07:17 UTC, ErnestsEida commented on config/routes.rb
> +  get "search", to: "search#search_query"
meginaju vienkarsi `get :search`, gan ari `get :search, only: [:show]` abi divi meta errorus 

> Missing :controller key on routes definition, please check your routes. (ArgumentError)

2021-12-06 11:24 UTC, pavels-gaimovics requested changes

2021-12-06 13:23 UTC, ErnestsEida commented on app/assets/stylesheets/search.scss
> +.search-results{
Pielaboju search.scss, parejos stylesheets visus izlaboju #56 PR

2021-12-06 14:31 UTC, pavels-gaimovics approved these changes
LGTM

2021-12-06 14:31 UTC, merged