Issue #73 - fix tags removal
ErnestsEida/R-edited pull request #74
Opened 2021-12-08 11:59 UTC by ErnestsEida

2021-12-08 13:33 UTC, pavels-gaimovics requested changes

2021-12-08 13:33 UTC, pavels-gaimovics commented on app/controllers/posts_controller.rb
> +      @post.tag_references.destroy_all
Jā Post modelim ir has_many :tag_references, dependent: :destroy
Tad šo rindiņu nevajadzes.

2021-12-08 13:33 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
> +    if json.present?
Your time has come.
Izlasi par "guard clause in Ruby" un turpmak šados gadijumos izmanto to

2021-12-08 14:51 UTC, pavels-gaimovics requested changes

2021-12-08 14:51 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
> +    return nil unless json.present?
Seriously!? "unless" kopā ar "present?"
Tev taču ir blank priekš tam!
Vai var tā?

`return if json.blank?`

2021-12-08 14:51 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
> +    return nil unless json.present?
Un ieliec jaunu rindu pēc viņa, lai būtu kods sadalits uz logiskiem blokiem

2021-12-08 14:51 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
> +      tags_params = JSON.parse(json)
Šeit tev četram rindam nepareiza atstarpe.

2021-12-08 20:28 UTC, ErnestsEida commented on app/models/concerns/tagable.rb
> +    return nil unless json.present?
vai tad ir kada dramatiska atskiriba starp present? un blank?. Man lasot tas likas ka diezgan logisks teikums.

2021-12-09 11:11 UTC, pavels-gaimovics requested changes

2021-12-09 11:11 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
>      tags_params = JSON.parse(json)
Man liekas tev kaut kā pietrukst... Vai ar šo kodu tev tiešam sanac dzest eksistejošos tagus?

2021-12-09 11:44 UTC, ErnestsEida commented on app/models/concerns/tagable.rb
>      tags_params = JSON.parse(json)
i think ka man tagus nevaig dzest, man vajag lai izdzesas tag_references prieks ta posta kuru dzes, jo tags tacu izmanto ari citi posti/community. Man itka tag_references dzesas kad izdzes.

2021-12-09 11:56 UTC, pavels-gaimovics requested changes

2021-12-09 11:56 UTC, pavels-gaimovics commented on app/models/concerns/tagable.rb
>      tags_params = JSON.parse(json)
Ka lietotais var nodzest eksistejošos tagus postam?

2021-12-09 11:57 UTC, pavels-gaimovics approved these changes
LGTM

2021-12-09 11:57 UTC, merged